### ISSUE TITLE
No module named 'mc'

### ISSUE THREAD

**Issue by shenxiangkei** [KyleZheng1997/simmatch#3]
Thank you very much for sharing your code, but I'm getting the following error in the runtime and I hope you can answer it.

When I run the simmatch.py, the ### error is as follows: ModuleNotFoundError: **`No module named 'mc'`** .

**Comment by KyleZheng1997** [comment]
Hello, "mc" is our internal module for speeding up the image io process, as I have mentioned in the read me file, you need to change the Dataset setting (ImagenetPercentV2 function in dataset/imagenet.py), and Pytorch DDP setting (dist_init function in util/dist_utils.py) for your server environment.

**Comment by shenxiangkei** [comment]
Thank you very much for answering my question at this late hour, but I still don't understand what exactly you mean by change. Can you tell me your WeChat or QQ? Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KyleZheng1997/simmatch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月8日(星期五) 晚上10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KyleZheng1997/simmatch] No module named 'mc' (Issue #3)





 
Hello, "mc" is our internal module for speeding up the image io process, as I have mentioned in the read me file, you need to change the Dataset setting (ImagenetPercentV2 function in dataset/imagenet.py), and Pytorch DDP setting (dist_init function in util/dist_utils.py) for your server environment.

**Comment by KyleZheng1997** [comment]
here is my email mingkaizheng@outlook.com, please send me your WeChat, I would like to help you later on.

**Comment by wyyfffff** [comment]
我下载了readme里面用来训练cifar10/100的代码，也遇到了这个问题，请问下这个地方要如何更改呢？

**Comment by kyle-1997** [comment]
As I have mentioned above, "mc" is our internal module for speeding up the image io process, but for the CIFAR dataset, I don't think we actually need it. you can just simply delete the related code. BTW, I just found a benchmark paper, "[USB: A Unified Semi-supervised learning Benchmark for CV, NLP, and Audio](https://arxiv.org/abs/2208.07204)" which has reproduced lots of SSL algorithms (including our SimMatch). You could also use their [referenced code](https://github.com/microsoft/Semi-supervised-learning) if my repository is confused for you.

**Comment by wyyfffff** [comment]
十分感谢

**Comment by syorami** [comment]
hi I'm having the same issue on reproducing the imagenet results. The question is I'm not sure whether my modification matches the original implementation and the imagenet experiment really takes a long time.

**Comment by kyle-1997** [comment]
> hi I'm having the same issue on reproducing the imagenet results. The question is I'm not sure whether my modification matches the original implementation and the imagenet experiment really takes a long time.

Sorry I just realized I missed your problem. Do you still have any questions? I'm very happy to help you out.

**Comment by syorami** [comment]
Thanks for your reply. I have succeeded in reproducing the results.
