### ISSUE TITLE
About _update_bank function

### ISSUE THREAD

**Issue by sybapp** [KyleZheng1997/simmatch#5]
Thanks very much for your contributions. But I have some trouble when I read the cifar-10 code(`semi.zip`).
```python
self.bank[:, index] = F.normalize(self.bank[:, index] * args.bank_m + k.t() * (1-args.bank_m))
```
Shouldn't the normalize here be normalized to the 0th dimension?

**Comment by KyleZheng1997** [comment]
Yes, you are right, we should normalize the tensor on 0th dimension. Sorry for the mistake.

**Comment by sybapp** [comment]
Thank you for your prompt reply and thanks again for your work.
